language: node_js
node_js:
  v10.0.0

services: mongodb

jobs:
  include:
    - stage: test
      before_install: echo $HOME && pwd && cd server
      install: npm install
      script: npm test
      script: nyc npm test && nyc report --reporter=text-lcov | coveralls
    - # stage name not required, will continue to use `test`
      before_install: cd client
      install: npm install
      script: npm test
