FROM node:10-stretch
RUN apt-get --yes update
RUN apt-get --yes install ffmpeg
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY package.json /usr/src/app/
RUN npm install
COPY . /usr/src/app
EXPOSE 3000
CMD [ "npm", "start" ]
